---
- name: Confiugre
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars_files:
    - ./defaults.yml
    - ./vars/static.yml

  pre_tasks:
    - name: Display system information
      ansible.builtin.debug:
        msg:
          - "Configuring macOS development environment"
          - "System: {{ ansible_facts.system | default('Unknown') }}"
          - "Model: {{ ansible_facts.model | default('Unknown') }}"
          - "Architecture: {{ ansible_facts.architecture }}"
          - "User: {{ ansible_user_id }}"

    - name: Fail if not on MacOS
      ansible.builtin.fail:
        msg: "This playbook is designed for macOS only"
      when: ansible_facts.system != "Darwin"

    - name: Ensure Xcode Command Line Tools are installed
      ansible.builtin.command:
        cmd: xcode-select --print-path
      register: xcode_path
      changed_when: false
      failed_when: false

    - name: Display Xcode Command Line Tools status
      ansible.builtin.debug:
        msg: |
          {% if xcode_path.rc == 0 %}
          Xcode Command Line Tools installed at: {{ xcode_path.stdout }}
          {% else %}
          Xcode Command Line Tools not found. Install with: xcode-select --install
          {% endif %}

  tasks:
    - name: Apply macOS system defaults
      ansible.builtin.import_tasks:
        file: tasks/defaults.yml
      tags:
        - defaults

    - name: Configure global settings and dotfiles
      ansible.builtin.import_tasks:
        file: tasks/global.yml
      tags:
        - global

    - name: Install Homebrew packages
      ansible.builtin.import_tasks:
        file: tasks/brew.yml
      tags:
        - brew

    - name: Install Mac App Store apps
      ansible.builtin.import_tasks:
        file: tasks/mas.yml
      tags:
        - mas

    - name: Configure Dock layout
      ansible.builtin.import_tasks:
        file: tasks/dock.yml
      tags:
        - dock

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "macOS development environment configuration completed!"
          - "Please restart your shell or run 'source ~/.zshrc' to apply shell changes"
          - "Some changes may require logging out and back in to take effect"
          - "Run 'brew doctor' if you encounter any Homebrew issues"

  handlers:
    - name: Restart Dock
      ansible.builtin.command: killall Dock
      listen: "restart dock"
      changed_when: true

    - name: Restart Finder
      ansible.builtin.command: killall Finder
      listen: "restart finder"
      changed_when: true
