---
- name: Confiugre
  hosts: localhost

  vars_files:
    - ./defaults.yml
    - ./vars/static.yml

  tasks:
    - name: Homebrew
      ansible.builtin.import_tasks:
        file: tasks/brew.yml

    - name: Global configuration
      ansible.builtin.import_tasks:
        file: tasks/global.yml
      tags:
        - global

    - name: Mac App Store
      ansible.builtin.import_tasks:
        file: tasks/mas.yml
      tags:
        - mas

    - name: Configure dock
      ansible.builtin.import_tasks:
        file: tasks/dock.yml
      tags:
        - dock

    - name: Run configuration script
      ansible.builtin.import_tasks:
        file: tasks/defaults.yml
      tags:
        - defaults
