- name: Update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Ensure all global homebrew packages are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ all_brew_packages }}"

- name: Ensure all global homebrew cask packages are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ all_brew_cask_packages }}"

- name: Ensure all global homebrew cask packages for macbooks are installed
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    sudo_password: "{{ ansible_become_password | default(omit) }}"
  loop: "{{ macbook_brew_cask_packages }}"
  when: ansible_model in macbook_model_identifiers

- name: Ensure all packages are upgraded
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
