---
# Create necessary directories
- name: Create .config directory structure in home
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ".config"
    - ".config/wezterm"
    - ".config/zed"
    - ".config/starship"
    - ".config/gitconfigs"

- name: Create SSH config directory with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Copy dotfiles to destination directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/"
    dest: "{{ dotfiles_dest | expanduser }}/"
    mode: preserve
    backup: false
  register: dotfiles_copy_result

- name: Create symlinks
  loop: "{{ symlinks | default([]) }}"
  loop_control:
    label: "{{ item.src }}"
  ansible.builtin.file:
    src: "{{ dotfiles_dest }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  when: symlinks is defined and symlinks | length > 0
