# Create necessary directories
- name: Create .config directory in home
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "$HOME/.config"
    - "$HOME/.config/wezterm"

# Create symlinks for dotfiles
- name: Clone dotfiles in home directory
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    version: "{{ dotfiles_repo_branch }}"
    dest: "{{ dotfiles_dest }}"

- name: Get stats of ssh config
  ansible.builtin.stat:
    path: "$HOME/.ssh/config"
  register: file_status

- name: Remove ssh config if it is not a symlink
  when: file_status.stat.exists and not file_status.stat.islnk
  ansible.builtin.file:
    path: "$HOME/.ssh/config"
    state: absent

- name: Create symlinks
  ansible.builtin.file:
    src: "{{ dotfiles_dest }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ symlinks }}"
