---
# Create necessary directories
- name: Create .config directory in home
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "$HOME/.config"
    - "$HOME/.config/wezterm"
    - "$HOME/.config/zed"
    - "$HOME/.config/starship"

- name: Copy dotfiles in home directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.dotfiles/"
    dest: "{{ dotfiles_dest }}"

- name: Create all symlinks
  ansible.builtin.include_tasks: global-symlinks.yml
  loop: "{{ symlinks }}"
  loop_control:
    extended: true
    extended_allitems: false
