---
# Create necessary directories
- name: Create .config directory in home
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "$HOME/.config"
    - "$HOME/.config/wezterm"

# Create symlinks for dotfiles
- name: Clone dotfiles in home directory
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    version: "{{ dotfiles_repo_branch }}"
    dest: "{{ dotfiles_dest }}"

- name: Create all symlinks
  ansible.builtin.include_tasks: global-symlinks.yml
  loop: "{{ symlinks }}"
  loop_control:
    extended: true
    extended_allitems: false

- name: Configure osx via script
  ansible.builtin.shell:
    cmd: source $HOME/.osx.sh
    creates: "$HOME/.osx.sh.done"
