---
# Create necessary directories
- name: Create .config directory in home
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "$HOME/.config"
    - "$HOME/.config/wezterm"
    - "$HOME/.config/zed"

- name: Copy dotfiles in home directory
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/.dotfiles/"
    dest: "{{ dotfiles_dest }}"

- name: Create all symlinks
  ansible.builtin.include_tasks: global-symlinks.yml
  loop: "{{ symlinks }}"
  loop_control:
    extended: true
    extended_allitems: false

- name: Stat .osx.sh.done
  ansible.builtin.stat:
    path: "$HOME/.osx.sh"
    follow: yes
    checksum_algorithm: sha256
  register: osx_file

- name: Configure osx via script
  ansible.builtin.shell:
    cmd: source $HOME/.osx.sh
  when: osx_file.stat.checksum != lookup('ansible.builtin.file', osx_file.stat.path + ".done", errors='ignore')
