---
- name: Ensure MAS cli is installed
  community.general.homebrew:
    name: mas
    state: present

- name: List installed apps
  ansible.builtin.command:
    cmd: mas list
  register: mas_list
  check_mode: false
  changed_when: false
  failed_when: false

- name: Create list of currently installed app IDs
  ansible.builtin.set_fact:
    installed_app_ids: "{{ mas_list.stdout_lines | map('regex_replace', '^(\\d+)\\s+.*$', '\\1') | list }}"
  when: mas_list.rc == 0

- name: Set empty list if no apps installed
  ansible.builtin.set_fact:
    installed_app_ids: []
  when: mas_list.rc != 0

- name: Install apps from App Store
  ansible.builtin.command:
    cmd: mas install "{{ item.id | default(item) }}"
  loop: "{{ mas_install_apps | default([]) }}"
  when:
    - (item.id | default(item) | string) not in installed_app_ids
  register: mas_install_result
  changed_when: mas_install_result.rc == 0
  failed_when:
    - mas_install_result.rc != 0
    - "'already installed' not in mas_install_result.stderr"

- name: Uninstall apps from App Store
  ansible.builtin.command:
    cmd: mas uninstall "{{ item.id | default(item) }}"
  loop: "{{ uninstall_apps | default([]) }}"
  when: (item.id | default(item) | string) in installed_app_ids
  register: mas_uninstall_result
  changed_when: mas_uninstall_result.rc == 0
  failed_when:
    - mas_uninstall_result.rc != 0
    - "'not installed' not in mas_uninstall_result.stderr"
