- name: Install MAS with brew
  homebrew:
    name: mas
    state: present

- name: List installed apps
  command: mas list
  register: mas_list
  check_mode: false
  changed_when: false

- name: Install listed apps
  command: mas install "{{ item.id | default(item) }}"
  with_items: "{{ apps }}"
  when: (item.id | default(item) | string) not in mas_list.stdout
