# TFSwitch
path+=("$HOME/bin")

# Global Environment Variables
export HOMEBREW_NO_ENV_HINTS=1

export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=1
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=''
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND=''

# Plugins
source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
# zsh-syntax-highlighting must load before zsh-history-substring-search for it to work properly
source "$(brew --prefix)/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Initialize zsh completion system
autoload -Uz compinit && compinit

# Case-insensitive completion configuration
# m:{a-z}={A-Z} - Match lowercase letters to uppercase (hello matches HELLO)
# m:{a-zA-Z}={A-Za-z} - Match any case to any other case (bidirectional)
# r:|[._-]=* r:|=* - Allow partial matching after dots, underscores, hyphens
# l:|=* r:|=* - Allow partial matching from left side of words
zstyle ':completion:*' matcher-list \
  'm:{a-z}={A-Z}' \
  'm:{a-zA-Z}={A-Za-z}' \
  'r:|[._-]=* r:|=*' \
  'l:|=* r:|=*'

# Enable interactive menu for completions (use arrow keys to navigate)
zstyle ':completion:*' menu select
# Use colors in completion menu (empty string uses default colors)
zstyle ':completion:*' list-colors ''

# NVM
export NVM_DIR="$HOME/.nvm"
    [ -s "$(brew --prefix)/opt/nvm/nvm.sh" ] && \. "$(brew --prefix)/opt/nvm/nvm.sh"

# PyENV
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"


# Aliases
alias awsp="source _awsp"
alias rosetta=arch -x86_64

alias k='kubectl'
alias ll='ls -laGh'

export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml
eval "$(starship init zsh)"
