---
- name: Ensure git-switcher is present
  homebrew:
    name: "theykk/tap/git-switcher"
    state: present

- name: Create gitconfigs directory
  command:
    cmd: git-switcher -h
  changed_when: false